uv run torchrun --standalone --nnodes=1 --nproc_per_node=1 run_train.py \
--diff_steps 2000 \
--lr 0.0001 \
--learning_steps 50000 \
--save_interval 2000 \
--seed 6868 \
--noise_schedule sqrt \
--hidden_dim 128 \
--bsz 1024 \
--microbatch 96 \
--dataset qqp \
--data_dir ./datasets/raw/QQP-Official \
--vocab bert \
--seq_len 128 \
--schedule_sampler lossaware \
--resume_checkpoint "None" \
--notes test-qqp \
--sc_rate 0.5 \
--rescale_max 1000